baseurl = "https://getgoetz.com"
languageCode = "en_GB"
title = "GetGoetz.com"
copyright = "<a href=\"/blog/2017/cli-commands/\" alt=\"Link to CLI command blog post\">&copy;</a> <span class=\"has-text-weight-semibold\">Goetz Epperlein</span> 2016 - 2019"
googleAnalytics = "UA-124600865-1"
theme = "bulmera"
paginate = 3
summarylength = 30

[author]
name = "Goetz Epperlein"
email = "now@getgoetz.com"

[taxonomies]
tag = "tags"

[params.meta]
keywords = [ "aws", "devops", "serverless", "amazon web service", "it consultant", "munich", "consultanting", "consultancy", "goetz", "epperlein", "goetz epperlein", "europe" ]

[params.design]
color = "#F86B61"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
  [privacy.instagram]
    simple = true
  [privacy.twitter]
    enableDNT = true
    simple = true
  [privacy.vimeo]
    simple = true
  [privacy.youtube]
    privacyEnhanced = true
