name = "Bulmera"
license = "MIT"
description = "Bulma based blog theme"
homepage = "https://getgoetz.com/"
tags = ["blog", "font awesome", "highlight.js"]
features = ["bulma", "responsive"]
min_version = "0.41"

[author]
  name = "Goetz Epperlein"
  homepage = "https://github.com/lony"
